version: "3"

services:
  frontend:
    container_name: frontend
    image: node:10.16.2-alpine
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
  userservice:
    container_name: userservice
    build:
      context: "./userservice"
      dockerfile: "dev.Dockerfile"
    command: "sh ./up.sh"
    volumes:
      - "./userservice:/go/src/user"
    ports: 
      - "8081:8081"
    working_dir: /go/src/user
    environment:
      - AES_KEY=${AES_KEY}
  db:
    image: "mongo:3.4.22-xenial"
    volumes:
      - "db:/data/db"
      - "configdb:/data/configdb"
    ports:
      - "27017:27017"
volumes:
  db:
  configdb: