version: "3.7"

services:
  web:
    build: "."
    restart: "always"
    command: "npm run dev"
    volumes:
      - ".:/app"
    ports: 
      - "3000:3000"
    environment:
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - SESSION_SIGNNATURE=${SESSION_SIGNNATURE}
      - NODE_ENV=development
  db:
    image: "mongo:3.4.22-xenial"
    restart: "always"
    volumes:
      - "db:/data/db"
      - "configdb:/data/configdb"
    ports:
      - "27017:27017"
volumes:
  db:
  configdb: