/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * pb/user.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *  
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 * 
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration = new Configuration();

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 * 
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface GatewayAuthRequest
 */
export interface GatewayAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof GatewayAuthRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayAuthRequest
     */
    password?: string;
}

/**
 * 
 * @export
 * @interface GatewayAuthResponse
 */
export interface GatewayAuthResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GatewayAuthResponse
     */
    ok?: boolean;
}


/**
 * UserServiceApi - fetch parameter creator
 * @export
 */
export const UserServiceApiFetchParamCreator = function (_configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GatewayAuthRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auth(body: GatewayAuthRequest, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling auth.');
            }
            const localVarPath = `/api/v1/user/auth`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"GatewayAuthRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserServiceApi - functional programming interface
 * @export
 */
export const UserServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {GatewayAuthRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auth(body: GatewayAuthRequest, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<GatewayAuthResponse> {
            const localVarFetchArgs = UserServiceApiFetchParamCreator(configuration).auth(body, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * UserServiceApi - factory interface
 * @export
 */
export const UserServiceApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {GatewayAuthRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        auth(body: GatewayAuthRequest, options?: any) {
            return UserServiceApiFp(configuration).auth(body, options)(fetch, basePath);
        },
    };
};

/**
 * UserServiceApi - object-oriented interface
 * @export
 * @class UserServiceApi
 * @extends {BaseAPI}
 */
export class UserServiceApi extends BaseAPI {
    /**
     * 
     * @param {GatewayAuthRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserServiceApi
     */
    public auth(body: GatewayAuthRequest, options?: any) {
        return UserServiceApiFp(this.configuration).auth(body, options)(this.fetch, this.basePath);
    }

}
